/**
 * Firebase Configuration
 * This file is AUTO-GENERATED from .env
 * DO NOT EDIT THIS FILE DIRECTLY
 * 
 * To update: Edit .env and run: npm run build:config
 */

// Firebase configuration - Generated from environment variables
const firebaseConfig = {
    apiKey: "AIzaSyCBN9mxhu4i7hEoMxeLy-6e7dBOWRV-K78",
    authDomain: "liquidovapeshop.firebaseapp.com",
    databaseURL: "https://liquidovapeshop-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "liquidovapeshop",
    storageBucket: "liquidovapeshop.firebasestorage.app",
    messagingSenderId: "410966783440",
    appId: "1:410966783440:web:ab8b96fdf4b81a790775d5",
    measurementId: "G-9VDR2HHTYJ"
};

// Initialize Firebase (using CDN version for compatibility)
let firebaseApp = null;
let firebaseDatabase = null;
let firebaseAuth = null;
let firebaseAnalytics = null;

/**
 * Initialize Firebase
 * @returns {Promise<Object>} Firebase app, database, auth, and analytics instances
 */
function initializeFirebase() {
    if (firebaseApp) {
        return Promise.resolve({
            app: firebaseApp,
            database: firebaseDatabase,
            auth: firebaseAuth,
            analytics: firebaseAnalytics
        });
    }

    // Check if Firebase is loaded
    if (typeof firebase === 'undefined') {
        return Promise.reject(new Error('Firebase SDK not loaded. Please include Firebase scripts.'));
    }

    try {
        // Initialize Firebase
        firebaseApp = firebase.initializeApp(firebaseConfig);
        firebaseDatabase = firebase.database();
        
        // Initialize Auth (check if available)
        if (firebase.auth) {
            firebaseAuth = firebase.auth();
        } else {
            console.warn('Firebase Auth not loaded. Make sure firebase-auth-compat.js is included.');
        }
        
        // Initialize Analytics (optional)
        if (firebase.analytics) {
            firebaseAnalytics = firebase.analytics();
        }

        return Promise.resolve({
            app: firebaseApp,
            database: firebaseDatabase,
            auth: firebaseAuth,
            analytics: firebaseAnalytics
        });
    } catch (error) {
        console.error('Error initializing Firebase:', error);
        return Promise.reject(error);
    }
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { initializeFirebase, firebaseConfig };
}

// Make available globally
window.firebaseConfig = { initializeFirebase, firebaseConfig };

